packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@firebase/util': true
  '@prisma/engines': false
  dooboolab-welcome: true
  esbuild: true
  msw: true
  prisma: false
  protobufjs: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - shadcn@4.8.3
  - date-fns@4.4.0
