#!/bin/sh
set -e

APP_DIR="/app"
CREDENTIALS_RELATIVE_PATH="${FIREBASE_CREDENTIALS_PATH:-storage/firebase-credentials.json}"

case "$CREDENTIALS_RELATIVE_PATH" in
  /*) CREDENTIALS_PATH="$CREDENTIALS_RELATIVE_PATH" ;;
  *) CREDENTIALS_PATH="$APP_DIR/$CREDENTIALS_RELATIVE_PATH" ;;
esac

if [ -n "$FIREBASE_CREDENTIALS_JSON" ]; then
  mkdir -p "$(dirname "$CREDENTIALS_PATH")"
  printf "%s" "$FIREBASE_CREDENTIALS_JSON" > "$CREDENTIALS_PATH"
  chmod 600 "$CREDENTIALS_PATH"
fi

cd "$APP_DIR"

if [ ! -f .env ]; then
  if [ -f .env.docker ]; then
    cp .env.docker .env
  elif [ -f .env.example ]; then
    cp .env.example .env
  fi
fi

set_env_value() {
  key="$1"
  value="$(printenv "$key" || true)"

  if [ -z "$value" ] || [ ! -f .env ]; then
    return
  fi

  # Multiline secrets should stay in the runtime environment. Writing them with
  # sed can break startup before Laravel can boot.
  if [ "$(printf '%s' "$value" | wc -l | tr -d ' ')" -gt 0 ]; then
    return
  fi

  dotenv_value="$value"
  if printf '%s' "$value" | grep -q '[[:space:]]'; then
    dotenv_value="\"$(printf '%s' "$value" | sed 's/\\/\\\\/g; s/"/\\"/g')\""
  fi

  escaped="$(printf '%s' "$dotenv_value" | sed 's/[\/&]/\\&/g')"

  if grep -q "^${key}=" .env; then
    sed -i "s/^${key}=.*/${key}=${escaped}/" .env
  else
    printf '\n%s=%s\n' "$key" "$dotenv_value" >> .env
  fi
}

for key in \
  APP_NAME APP_ENV APP_KEY APP_DEBUG APP_URL FRONTEND_URL \
  DB_CONNECTION DB_HOST DB_PORT DB_DATABASE DB_USERNAME DB_PASSWORD \
  SESSION_DRIVER QUEUE_CONNECTION CACHE_STORE CACHE_DRIVER BROADCAST_CONNECTION FILESYSTEM_DISK \
  REDIS_CLIENT REDIS_HOST REDIS_PASSWORD REDIS_PORT REDIS_DB REDIS_CACHE_DB \
  MAIL_MAILER RESEND_API_KEY MAIL_HOST MAIL_PORT MAIL_USERNAME MAIL_PASSWORD MAIL_SCHEME MAIL_FROM_ADDRESS MAIL_FROM_NAME \
  PUSHER_APP_ID PUSHER_APP_KEY PUSHER_APP_SECRET PUSHER_APP_CLUSTER PUSHER_APP_TLS \
  OPENAI_API_KEY OPENAI_VISION_MODEL VISION_EMBEDDING_URL \
  CLOUDINARY_CLOUD_NAME CLOUDINARY_API_KEY CLOUDINARY_API_SECRET \
  PAYMONGO_SECRET_KEY PAYMONGO_WEBHOOK_SECRET PAYMONGO_LIVE_SECRET_KEY PAYMONGO_LIVE_PUBLIC_KEY PAYMONGO_LIVE_WEBHOOK_SECRET \
  ZQ_API_BASE_URL ZQ_API_KEY ZQ_TIMEOUT \
  XDE_BASE_URL XDE_BOOK_PATH XDE_TRACK_PATH XDE_API_KEY XDE_TOKEN XDE_TIMEOUT XDE_DEFAULT_WEIGHT XDE_DEFAULT_LENGTH XDE_DEFAULT_WIDTH XDE_DEFAULT_HEIGHT XDE_DEFAULT_VOLUME XDE_PACKAGE_SIZE XDE_PACKAGE_TYPE XDE_DELIVERY_TYPE XDE_SHIPPING_TYPE XDE_JOURNEY_TYPE XDE_TRANSPORT_MODE XDE_PORT_CODE XDE_SHIPMENT_PROVIDER XDE_MERCHANT_NAME XDE_MERCHANT_ADDRESS XDE_MERCHANT_MOBILE XDE_MERCHANT_EMAIL XDE_MERCHANT_PROVINCE XDE_MERCHANT_CITY \
  JT_API_BASE_URL JT_CUSTOMER_CODE JT_API_ACCOUNT JT_API_PASSWORD JT_PRIVATE_KEY JT_IS_SANDBOX \
  JNT_BASE_URL JNT_BOOK_PATH JNT_TRACK_PATH JNT_CUSTOMER_CODE JNT_API_ACCOUNT JNT_PASSWORD JNT_PRIVATE_KEY JNT_IS_SANDBOX JNT_PASSWORD_SUFFIX JNT_SERVICE_TYPE JNT_COUNTRY_CODE JNT_ORDER_TYPE JNT_EXPRESS_TYPE JNT_DELIVERY_TYPE JNT_GOODS_TYPE JNT_PRICE_CURRENCY JNT_OPERATE_TYPE JNT_DEFAULT_WEIGHT JNT_DEFAULT_LENGTH JNT_DEFAULT_WIDTH JNT_DEFAULT_HEIGHT JNT_DEFAULT_VOLUME JNT_OFFER_FEE JNT_SENDER_NAME JNT_SENDER_COMPANY JNT_SENDER_PHONE JNT_SENDER_MOBILE JNT_SENDER_EMAIL JNT_SENDER_POST_CODE JNT_SENDER_PROVINCE JNT_SENDER_CITY JNT_SENDER_ADDRESS JNT_TIMEOUT JNT_WEBHOOK_SECRET JNT_HEADER_DIGEST_OVERRIDE \
  USER_LOGIN_CLOUDFLARE_TURNSTILE_SECRET USER_SIGNUP_CLOUDFLARE_TURNSTILE_SECRET ADMIN_LOGIN_CLOUDFLARE_TURNSTILE_SECRET USER_FORGOT_PASSWORD_CLOUDFLARE_TURNSTILE_SECRET \
  GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET GOOGLE_REDIRECT_URL FACEBOOK_CLIENT_ID FACEBOOK_CLIENT_SECRET FACEBOOK_REDIRECT_URL \
  GOOGLE_DRIVE_FOLDER_ID GOOGLE_DRIVE_FOLDER_URL GOOGLE_DRIVE_SERVICE_ACCOUNT_EMAIL GOOGLE_DRIVE_SERVICE_ACCOUNT_PRIVATE_KEY_B64 GOOGLE_DRIVE_DESKTOP_BACKUP_PATH GOOGLE_DRIVE_OAUTH_CLIENT_ID GOOGLE_DRIVE_OAUTH_CLIENT_SECRET GOOGLE_DRIVE_OAUTH_REFRESH_TOKEN DB_DAILY_EXPORT_ENABLED \
  FIREBASE_CREDENTIALS_JSON FIREBASE_CREDENTIALS_PATH FIREBASE_PROJECT_ID ONESIGNAL_APP_ID ONESIGNAL_REST_API_KEY MOBILE_PAYMENT_SUCCESS_URL MOBILE_PAYMENT_CANCEL_URL
do
  set_env_value "$key"
done

if [ ! -f vendor/autoload.php ]; then
  composer install --no-interaction --prefer-dist
fi

if [ ! -d node_modules/.bin ]; then
  npm install
fi

if grep -q "^APP_KEY=$" .env 2>/dev/null; then
  php artisan key:generate --force >/dev/null 2>&1 || true
fi

php artisan optimize:clear >/dev/null 2>&1 || true
php artisan config:clear >/dev/null 2>&1 || true
php artisan cache:clear >/dev/null 2>&1 || true

php artisan migrate --force || true

exec "$@"
