<?php

namespace Database\Seeders;

use App\Models\WebPageContent;
use Illuminate\Database\Seeder;

class DreamBuildContentDeckV2Seeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'type' => 'dreambuild-hero',
                'key' => 'hero-main',
                'title' => 'One team for your entire interior - design, supply, and installation',
                'subtitle' => 'All-in-One Interior Solutions',
                'body' => 'DreamBuild is the only partner you need between bare space and finished home. We design the interior, source and supply every piece through our proprietary international supply chain, and install it all - turnover-ready, on one timeline, under one accountable team.',
                'button_text' => 'Explore Solutions',
                'link_url' => '#solutions',
                'sort' => 0,
                'active' => true,
                'payload' => [
                    'eyebrow' => 'All-in-One Interior Solutions',
                    'alternate_headline' => 'From design to done. One team, one accountable hand.',
                    'primary_button_text' => 'Explore Solutions',
                    'primary_button_url' => '#solutions',
                    'secondary_button_text' => 'View Projects',
                    'secondary_button_url' => '#projects',
                    'stat_1_value' => 'End-to-end',
                    'stat_1_label' => 'design, supply, and installation under one roof',
                    'stat_2_value' => '20+ yrs',
                    'stat_2_label' => 'direct international sourcing experience',
                    'stat_3_value' => '1 team',
                    'stat_3_label' => 'one contract, one timeline, zero finger-pointing',
                    'pure_numbers' => '3-in-1 services · 20+ years sourcing · 24-hr response time',
                    'caption_1' => 'Turnover-Ready Living Room',
                    'caption_2' => 'Designed · Supplied · Installed',
                ],
            ],
            [
                'type' => 'dreambuild-services',
                'key' => 'interior-design',
                'title' => 'Interior Design',
                'subtitle' => 'The blueprint of your home\'s character.',
                'body' => 'Space planning, material direction, and a complete visual language - designed around how you actually live, and engineered to be sourced and installed without compromise.',
                'sort' => 0,
                'active' => true,
                'payload' => [
                    'eyebrow' => 'Interior Solutions',
                    'section_headline' => 'Everything between bare space and finished home.',
                    'section_intro' => 'Most projects fail in the handoffs - designer to supplier to installer. We removed the handoffs. Three integrated solutions, one accountable team.',
                    'service_number' => '01',
                    'bullets' => "Space planning with lifestyle-based zoning\nMaterial, color, and finish coordination\nFurniture, lighting, and styling direction",
                ],
            ],
            [
                'type' => 'dreambuild-services',
                'key' => 'sourcing-supply',
                'title' => 'Sourcing & Supply',
                'subtitle' => 'We don\'t hand you a shopping list - we deliver the pieces.',
                'body' => 'Two decades of direct factory relationships through our proprietary international supply chain mean designer-grade furniture, lighting, and finishing materials at prices showrooms can\'t touch.',
                'sort' => 1,
                'active' => true,
                'payload' => [
                    'service_number' => '02',
                    'bullets' => "Direct-from-factory furniture, lighting, and fixtures\nFinishing materials, hardware, and soft furnishings\nConsolidated shipping, QC inspection, and delivery",
                ],
            ],
            [
                'type' => 'dreambuild-services',
                'key' => 'installation-finishing',
                'title' => 'Installation & Finishing',
                'subtitle' => 'The last mile is where most projects fall apart - so we own it.',
                'body' => 'Our crews install, assemble, and style everything we design and supply, then hand you a home that\'s photo-ready on day one.',
                'button_text' => 'Book a Free Consult',
                'link_url' => '#contact',
                'sort' => 2,
                'active' => true,
                'payload' => [
                    'service_number' => '03',
                    'bullets' => "Furniture, fixture, and built-in installation\nCurtains, lighting, and accessory fit-out\nFinal styling, QC walkthrough, and turnover",
                    'cta_text' => 'Need the full package - or just one part of it?',
                ],
            ],
            [
                'type' => 'dreambuild-gallery',
                'key' => 'living-room-styling',
                'title' => 'Living Room Styling',
                'sort' => 0,
                'active' => true,
                'payload' => ['file_name' => 'db_gallery_livingroomstyling_01.jpg', 'shot_description' => 'Sofa vignette: layered cushions, throw, side lamp on', 'orientation' => 'Square 1:1', 'alt' => 'Living Room Styling'],
            ],
            [
                'type' => 'dreambuild-gallery',
                'key' => 'dining-space-layers',
                'title' => 'Dining Space Layers',
                'sort' => 1,
                'active' => true,
                'payload' => ['file_name' => 'db_gallery_diningspacelayers_01.jpg', 'shot_description' => 'Dining table set casually, pendant light featured', 'orientation' => 'Square 1:1', 'alt' => 'Dining Space Layers'],
            ],
            [
                'type' => 'dreambuild-gallery',
                'key' => 'bedroom-material-story',
                'title' => 'Bedroom Material Story',
                'sort' => 2,
                'active' => true,
                'payload' => ['file_name' => 'db_gallery_bedroommaterialstory_01.jpg', 'shot_description' => 'Bed linen texture and headboard, warm bedside light, bed steamed', 'orientation' => 'Square 1:1', 'alt' => 'Bedroom Material Story'],
            ],
            [
                'type' => 'dreambuild-gallery',
                'key' => 'modern-kitchen-detail',
                'title' => 'Modern Kitchen Detail',
                'sort' => 3,
                'active' => true,
                'payload' => ['file_name' => 'db_gallery_modernkitchendetail_01.jpg', 'shot_description' => 'Countertop and cabinet hardware close-up, one styled tray', 'orientation' => 'Square 1:1', 'alt' => 'Modern Kitchen Detail'],
            ],
            [
                'type' => 'dreambuild-gallery',
                'key' => 'lounge-accent-composition',
                'title' => 'Lounge Accent Composition',
                'sort' => 4,
                'active' => true,
                'payload' => ['file_name' => 'db_gallery_loungeaccent_01.jpg', 'shot_description' => 'Accent chair, wall art, and plant grouping', 'orientation' => 'Square 1:1', 'alt' => 'Lounge Accent Composition'],
            ],
            [
                'type' => 'dreambuild-gallery',
                'key' => 'warm-neutral-interior',
                'title' => 'Warm Neutral Interior',
                'sort' => 5,
                'active' => true,
                'payload' => [
                    'file_name' => 'db_gallery_warmneutral_01.jpg',
                    'shot_description' => 'Widest, calmest portfolio shot, generous negative space',
                    'orientation' => 'Square 1:1',
                    'alt' => 'Warm Neutral Interior',
                    'section_eyebrow' => 'Interior Gallery',
                    'section_headline' => 'Designed, supplied, and installed by one team.',
                    'helper_line' => '6 turnover-ready spaces',
                    'link_text' => 'See All Projects',
                ],
            ],
            [
                'type' => 'dreambuild-projects',
                'key' => 'warm-minimalist-residence',
                'title' => 'Warm Minimalist Residence',
                'body' => 'The brief: a family home that felt busy and visually heavy. We designed a warm minimalist direction - oak, soft whites, black accents - then sourced every piece through our international supply chain and installed it down to the last shelf. One team, one timeline. The family changed nothing on turnover day.',
                'sort' => 0,
                'active' => true,
                'payload' => ['tag' => 'Full Solution · Design to Installation', 'location' => 'Metro Manila', 'timeline' => 'Timeline confirmed per project', 'scope' => "Design\nSupply\nInstallation", 'card_size' => 'tall'],
            ],
            [
                'type' => 'dreambuild-projects',
                'key' => 'soft-luxe-condo-suite',
                'title' => 'Soft Luxe Condo Suite',
                'body' => 'The brief: a compact condo that should feel like a hotel suite. We designed layered neutrals with brass details, supplied furniture and lighting direct from factory partners, and our crew installed and styled the unit to photo-ready. The owner received keys to a finished home - not a project to manage.',
                'sort' => 1,
                'active' => true,
                'payload' => ['tag' => 'Full Solution · Urban Living', 'location' => 'Metro Manila', 'timeline' => 'Timeline confirmed per project', 'scope' => "Design\nSupply\nInstallation", 'card_size' => 'short'],
            ],
            [
                'type' => 'dreambuild-projects',
                'key' => 'contemporary-family-home',
                'title' => 'Contemporary Family Home',
                'body' => 'The brief: a growing family with an aging layout. We re-zoned the common areas, refined the finish palette, and supplied furniture, lighting, and materials at direct-sourced pricing - coordinated with the family\'s own renovation team for a seamless fit-out.',
                'sort' => 2,
                'active' => true,
                'payload' => ['tag' => 'Design + Supply', 'location' => 'Metro Manila', 'timeline' => 'Timeline confirmed per project', 'scope' => "Design\nSourcing & Supply", 'card_size' => 'short'],
            ],
            [
                'type' => 'dreambuild-projects',
                'key' => 'neutral-entertaining-space',
                'title' => 'Neutral Entertaining Space',
                'body' => 'The brief: a living and dining area that hosted often but never felt finished. Working from the client\'s design direction, we sourced the full furniture and decor package, then installed and styled it - texture-rich, guest-ready, and entirely managed for them.',
                'sort' => 3,
                'active' => true,
                'payload' => [
                    'tag' => 'Supply + Installation',
                    'location' => 'Metro Manila',
                    'timeline' => 'Timeline confirmed per project',
                    'scope' => "Supply\nInstallation",
                    'card_size' => 'tall',
                    'section_eyebrow' => 'Featured Projects',
                    'section_headline' => 'Spaces we took from bare to beautiful.',
                    'footer_line' => 'Showing 4 of our featured projects',
                    'footer_link_text' => 'See full portfolio',
                ],
            ],
            [
                'type' => 'dreambuild-blogs',
                'key' => 'why-sourcing-your-own-furniture-costs-more',
                'title' => 'Why Sourcing Your Own Furniture Usually Costs More',
                'subtitle' => 'Showroom markups, mismatched deliveries, and the hidden cost of your own time. Here\'s the real math behind direct-sourced interiors.',
                'sort' => 0,
                'active' => true,
                'payload' => ['category' => 'Sourcing', 'slug' => 'why-sourcing-your-own-furniture-costs-more', 'read_time' => '5 min read', 'hero_file_name' => 'db_blog_sourcingcosts_01.jpg'],
            ],
            [
                'type' => 'dreambuild-blogs',
                'key' => 'complete-guide-neutral-color-palettes',
                'title' => 'The Complete Guide to Neutral Color Palettes',
                'subtitle' => 'Understanding undertones, creating depth with neutrals, and avoiding the mistakes that make spaces feel flat.',
                'sort' => 1,
                'active' => true,
                'payload' => ['category' => 'Color Theory', 'slug' => 'complete-guide-neutral-color-palettes', 'read_time' => '7 min read', 'hero_file_name' => 'db_blog_neutralpalettes_01.jpg'],
            ],
            [
                'type' => 'dreambuild-blogs',
                'key' => 'design-to-done-turnover-ready',
                'title' => 'Design to Done: What "Turnover-Ready" Actually Means',
                'subtitle' => 'A finished design file isn\'t a finished home. Here\'s everything that happens between approval and the day you get your keys.',
                'sort' => 2,
                'active' => true,
                'payload' => ['category' => 'Process', 'slug' => 'design-to-done-turnover-ready', 'read_time' => '6 min read', 'hero_file_name' => 'db_blog_designtodone_01.jpg'],
            ],
            [
                'type' => 'dreambuild-blogs',
                'key' => 'lighting-layers-filipino-homes',
                'title' => 'Lighting Layers: Ambient, Task, and Accent for Filipino Homes',
                'subtitle' => 'Why one ceiling light is never enough, and how three layers of light turn an ordinary room into one that feels designed.',
                'sort' => 3,
                'active' => true,
                'payload' => ['category' => 'Styling Guide', 'slug' => 'lighting-layers-filipino-homes', 'read_time' => '5 min read', 'hero_file_name' => 'db_blog_lightinglayers_01.jpg'],
            ],
            [
                'type' => 'dreambuild-blogs',
                'key' => 'renovation-sequence-before-spending',
                'title' => 'The Renovation Sequence: What to Decide Before You Spend a Single Peso',
                'subtitle' => 'The order of decisions matters more than the budget. The sequence we use to protect clients from expensive do-overs.',
                'sort' => 4,
                'active' => true,
                'payload' => ['category' => 'Renovation', 'slug' => 'renovation-sequence-before-spending', 'read_time' => '6 min read', 'hero_file_name' => 'db_blog_renovationsequence_01.jpg'],
            ],
            [
                'type' => 'dreambuild-blogs',
                'key' => 'five-materials-home-feel-expensive',
                'title' => 'Five Materials That Make a Home Feel Expensive',
                'subtitle' => 'It\'s not about spending more - it\'s where texture, grain, and weight show up. These five materials do the heavy lifting.',
                'sort' => 5,
                'active' => true,
                'payload' => [
                    'category' => 'Materials',
                    'slug' => 'five-materials-home-feel-expensive',
                    'read_time' => '5 min read',
                    'hero_file_name' => 'db_blog_fivematerials_01.jpg',
                    'section_eyebrow' => 'DreamBuild Journal',
                    'section_headline' => 'Design notes for rooms with intention.',
                    'section_intro' => 'Editorial guides, sourcing intelligence, and finish decisions - written by the team that designs, supplies, and installs homes every week.',
                    'admin_note' => 'Unpublish the two test posts first: "19 blog examples..." and "Test Blogs Post".',
                ],
            ],
            [
                'type' => 'dreambuild-testimonials',
                'key' => 'testimonial-collection-instructions',
                'title' => 'What clients say.',
                'subtitle' => 'Client Testimonials',
                'body' => 'Real feedback from homeowners who handed us the whole project - and got back a finished home.',
                'sort' => 0,
                'active' => false,
                'payload' => [
                    'collection_message' => 'Hi [Name]! We\'re updating the DreamBuild website and would love to feature your home. Could you share 2-3 sentences on how the space feels now and what it was like having one team handle the design, supply, and installation? We\'d credit you as [First Name + Last Initial] only. Thank you!',
                    'format' => '"[Their words, 1-3 sentences, lightly edited for grammar only.]" - [First Name] [L]., Homeowner · Verified Client',
                    'note' => 'Keep inactive until real client quotes are collected. Nudge for convenience, one contact person, and no supplier-chasing.',
                ],
            ],
            [
                'type' => 'dreambuild-contact',
                'key' => 'contact-main',
                'title' => 'Ready for a home that\'s handled end to end?',
                'subtitle' => 'LET\'S TALK · Start Your Project',
                'body' => 'Tell us about your space - bare unit, tired interior, or anything in between. We\'ll get back to you within 24 hours to set up a free consultation.',
                'button_text' => 'Send Message',
                'sort' => 0,
                'active' => true,
                'payload' => [
                    'email' => 'hello@dreambuilddesignstudio.com',
                    'phone' => '+63 997 875 3004',
                    'address' => 'Metro Manila, Philippines',
                    'response_time' => 'Within 24 hours',
                    'status_badge' => 'Currently accepting new projects',
                    'need_options' => "Full Solution - Design to Installation\nInterior Design Only\nSourcing & Supply\nInstallation & Finishing\nNot sure yet",
                    'microcopy' => 'No commitment. We\'ll reach out to learn more before anything begins.',
                    'footer_descriptor' => 'All-in-one interior solutions - we design modern residential spaces, supply every piece through our proprietary international supply chain, and install it all, turnover-ready.',
                    'legal_line' => '© 2026 DreamBuild Design Studio. All rights reserved.',
                    'launch_note' => 'Publish real Privacy Policy and Terms pages before launch - the current links go nowhere.',
                ],
            ],
        ];

        $keptIds = [];

        foreach ($items as $item) {
            $content = WebPageContent::query()->updateOrCreate(
                [
                    'wpc_type' => $item['type'],
                    'wpc_key' => $item['key'],
                ],
                [
                    'wpc_title' => $item['title'] ?? null,
                    'wpc_subtitle' => $item['subtitle'] ?? null,
                    'wpc_body' => $item['body'] ?? null,
                    'wpc_image_url' => $item['image_url'] ?? null,
                    'wpc_link_url' => $item['link_url'] ?? null,
                    'wpc_button_text' => $item['button_text'] ?? null,
                    'wpc_payload' => $item['payload'] ?? null,
                    'wpc_sort' => (int) ($item['sort'] ?? 0),
                    'wpc_status' => (bool) ($item['active'] ?? true),
                    'wpc_start_at' => null,
                    'wpc_end_at' => null,
                ],
            );

            $keptIds[] = (int) $content->wpc_id;
        }

        WebPageContent::query()
            ->where('wpc_type', 'like', 'dreambuild-%')
            ->whereNotIn('wpc_id', $keptIds)
            ->update(['wpc_status' => false]);
    }
}
